### PR TITLE
[misc] fix module importing

### PR DESCRIPTION
**Pull request by das7pad**
The `index.js` entry point has been removed as part of the decaff process https://github.com/overleaf/metrics-module/commit/c597525ad34f5d8f746623160b7e404a6afc8ac7#diff-168726dbe96b3ce427e7fedce31bb0bc. Using a package.json entry skips the redirect from `index.js` to `metrics.js`.

### CODE REVIEW

**Comment by jdleesmiller** [comment]
How would you feel about renaming `metrics.js` to `index.js` to more closely follow the usual conventions? (Clearly this works, too.)

**Comment by das7pad** [comment]
> How would you feel about renaming `metrics.js` to `index.js`

I have not strong opinion on that. @briangough WDYT?

> to more closely follow the usual conventions

Like having all the source files on the top-level? ;)

**Comment by briangough** [comment]
> > How would you feel about renaming `metrics.js` to `index.js`
> 
> I have not strong opinion on that. @briangough WDYT?

Yes, I think it is cleaner to rename `metrics.js` to `index.js`.

**Comment by das7pad** [comment]
> Yes, I think it is cleaner to rename `metrics.js` to `index.js`.

Done and force-pushed.

**Pull request merged**
